# Generated by Django 4.0.2 on 2022-04-21 05:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0002_mascota'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosteoBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=100)),
                ('mascota', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('texto', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/blogs/')),
            ],
        ),
    ]
